language: java
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
  - tar -zxf android-sdk_r18-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android update sdk --filter 1,2,8,9 --no-ui --force
  # Once we have downloaded the essential tools more targets are available for download, so go and get what we need.
  - android update sdk --filter android-8 --no-ui --force
  # now get a runtime environment, the latest revision of Android (4.2.2) should do.
  - android update sdk --filter android-17,sysimg-17,tools,platform-tools,build-tools-17.0.0 --no-ui --force

script: "./buildstuff.sh"

